apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: timoni-runner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: timoni-runner
subjects:
  - kind: ServiceAccount
    name: timoni-runner
    namespace: timoni-system
