apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: chuck-norris-backend
  namespace: flux-system
spec:
  interval: 5m
  path: ./deploy
  prune: true
  wait: true
  timeout: 3m
  sourceRef:
    kind: GitRepository
    name: iac-chucknorris-backend
  dependsOn:
    - name: infra-traefik
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: chuck-norris-backend
      namespace: chuck-norris
