apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: iac-chucknorris-frontend
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/filhype-organization/iac-chucknorris-frontend
  ref:
    branch: main
