---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-tunnel-token
  namespace: ingress
spec:
  encryptedData:
    token: AgBC5TzvOrwAk6kTKULE0M39VNMLUIw9a4RbNXt/ujuQdmUB877gXg3AgBcLESVhOtBMZc3CgBs4vAM+Yk0Ta0vmYpjz39gM0u6BZXiSULt/cH4HwiMqkC6yWcSH+W5QNEa8MXdfb85zr8/WafxmCF5SBJd9zjhvPp84K8nEmAvA/c8CMhXf0KYLZGNja3hLJcbNblKRNNqUbRy8kjktgQ/QjtIOPEZGVnFzZP2Ygscvd9GPZGSKx7QRRSQcqnzArvdFNhuPU3ulYUHe0WE1HQoICMCDHgL0IS7Nn3rM4I3a0hfAw9RDbXnphZc9raaxaLfjoT1XXgSRnJV9XQYDUeN2p4CROOhzXqSnmWJ+VUUwXpCms83PwpvyuHvWCwYQoNbbDDdNsn95hvAngdNXNHJvn4V8yVTEFHKxSaKMIofUY7b4qyc8n7eKGCwOw/gVhIFX7HExGGJNWYozmY+UA6L26uR6XeIxY4pYT4k0OFdInaXOlqMuT46aGL7agPdyUlJ68/9OkQuQc3dNhhaE2lc22E4E8VeeeUg3zJr2M5zWCv1mbMtYFWeHwWkjYjGUwFJMCdxukhhTsj0HIgTBkg19zW5NvZCqA0UOgfxxyspDTPe+5ozc0MjIS5LLRJCf7VNFpM2YLuD9wsTxjpWSQkENHwgNaqmEP0/0MNFDszR2oMfnuZOM2npIQjf/7SUPeOXUFQ8jqa9OJ0PWG+OruVPEPc7qK8TE8MC7z0ZbB9fqHwqaald4Y6qo0ZMsbW1OSUvbAOgltKYs7oNHUFBHNEmioNFNbOPhotk7DAwkaHnNB4NXu1Iqky4LflFyqWqu/HeIkC1783+4YCjqOXNoRxFefb9HIoKJvCyUukzN05eSEyrYcmb+Sf5s5YdMbS86jH2BY2w/nXWSoRCDrstlLI+G1HARjNRX4LByKYJGHlZmH4WfP5RO1ENQ
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-tunnel-token
      namespace: ingress
